Update detail
ajaystha42/soundWave pull request #29
Opened 2023-07-24 15:55 UTC by gaurabpokharel

contact-us

2023-07-24 16:45 UTC, ajaystha42 commented
@gaurabpokharel  please solve conflicts before sending PR.

2023-07-25 17:24 UTC, gaurabpokharel commented
contact us page

2023-07-25 17:28 UTC, ajaystha42 requested changes

2023-07-25 17:28 UTC, ajaystha42 commented on html/contactUs.html
> -      $("#logout").show();
why removing this? @gaurabpokharel

2023-07-25 17:28 UTC, ajaystha42 commented on php/login.php
> +    echo $email ;
these are not necessary @gaurabpokharel

2023-07-25 19:05 UTC, merged